[package]
name = "sam-rbx/punch-monsters"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
authors = ["Runic", "perikov"]
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.4"
Component = "r-unic/componentize@0.4.7"
Array = "r-unic/array@0.2.7"
Signal = "sleitnick/signal@^1"
Input = "sleitnick/input@^2"
Janitor = "howmanysmall/janitor@^1.15"